### ISSUE TITLE
Überschreibung der Result Fields funktionieren nicht

### ISSUE THREAD

**Issue by Lauflust** [plentymarkets/plugin-ceres-coconut#2]
Der vorhandene Code um die Result Fields zu überschreiben funktionieren nicht.
https://github.com/plentymarkets/plugin-ceres-coconut/blob/4b68a313065aed516ff31fccc1b10a80bac2bffc/src/Providers/CeresCoconutServiceProvider.php#L325-L377

Es funktioniert wenn man folgenden Code verwendet:
`$dispatcher->listen( 'IO.ResultFields.*', function(ResultFieldTemplate $templateContainer)`

@plentymarkets/ceres-io

**Comment by lks-mtzn** [comment]
Ist mit dem PR behoben. 

https://github.com/plentymarkets/plugin-ceres-coconut/pull/4

**Comment by Lauflust** [comment]
Super besten Dank!
Testen kann ich das jetzt nicht, da ich schon eine eigene Lösung habe.
